server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/emp?createDatabaseIfNotExist=true
    username: root
    password: Anish@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  
logging:
  file:
    name: "app.log"
    clean-history-on-start: true
  level:
    org: info